"""Import Paprika .paprikarecipes into src/chatRecipes.ts (chat-only, no UI)."""
from __future__ import annotations

import argparse
import gzip
import json
import re
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "src" / "chatRecipes.ts"
DEFAULT_SEARCH = Path(r"C:\Users\loewe\OneDrive\Desktop\Bewerbungsunterlagen\2026")


def load_paprika_json(raw: bytes) -> dict:
    try:
        return json.loads(gzip.decompress(raw))
    except OSError:
        return json.loads(raw.decode("utf-8"))


def paprika_to_recipe(data: dict) -> dict | None:
    name = (data.get("name") or "").strip()
    if not name:
        return None
    ingredients = (data.get("ingredients") or "").strip()
    directions = (data.get("directions") or "").strip()
    if not ingredients and not directions:
        return None

    cats = data.get("categories") or []
    if isinstance(cats, list):
        categories = [str(c).strip() for c in cats if str(c).strip()]
    else:
        categories = []

    recipe = {
        "name": name,
        "ingredients": ingredients,
        "directions": directions,
    }
    for key, src in [
        ("servings", "servings"),
        ("prepTime", "prep_time"),
        ("cookTime", "cook_time"),
        ("notes", "notes"),
    ]:
        val = data.get(src)
        if val and str(val).strip():
            recipe[key] = str(val).strip()
    if categories:
        recipe["categories"] = categories
    return recipe


def find_export(path: Path | None) -> Path:
    if path and path.exists():
        return path
    if path and path.suffix == "":
        for ext in ("*.paprikarecipes", "*.paprikarecipe"):
            hits = sorted(path.glob(ext))
            if hits:
                return hits[0]

    for folder in (DEFAULT_SEARCH, REPO):
        for ext in ("*.paprikarecipes", "*.paprikarecipe"):
            hits = sorted(folder.glob(ext))
            if hits:
                return hits[0]
    raise FileNotFoundError(
        "Keine .paprikarecipes Datei gefunden. "
        "Export aus Paprika ablegen oder Pfad als Argument angeben."
    )


def extract_recipes(archive: Path, category_filter: str | None) -> list[dict]:
    recipes: list[dict] = []
    cat_lower = category_filter.lower() if category_filter else None

    with zipfile.ZipFile(archive, "r") as zf:
        for info in zf.infolist():
            if info.is_dir():
                continue
            name = info.filename.lower()
            if not (name.endswith(".paprikarecipe") or name.endswith(".json")):
                continue
            raw = zf.read(info.filename)
            try:
                data = load_paprika_json(raw)
            except (json.JSONDecodeError, OSError):
                continue
            recipe = paprika_to_recipe(data)
            if not recipe:
                continue
            if cat_lower:
                cats = [c.lower() for c in recipe.get("categories", [])]
                if not any(cat_lower in c for c in cats):
                    continue
            recipes.append(recipe)

    recipes.sort(key=lambda r: r["name"].lower())
    return recipes


def ts_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def emit_ts(recipes: list[dict]) -> str:
    header = """/**
 * Küchen-Rezepte – nur für den Chatbot (System-Prompt + Backup-Antworten).
 * Nicht in der App-Oberfläche sichtbar.
 *
 * Befüllen:
 *   python scripts/import_paprika_recipes.py "Pfad/zu/Export.paprikarecipes"
 * Optional nur Kategorie «Bewerbung» in Paprika:
 *   python scripts/import_paprika_recipes.py Export.paprikarecipes --category Bewerbung
 */

export type ChatRecipe = {
  name: string;
  servings?: string;
  prepTime?: string;
  cookTime?: string;
  ingredients: string;
  directions: string;
  notes?: string;
  categories?: string[];
};

/** Auto-generated by scripts/import_paprika_recipes.py */
export const ChatRecipes: ChatRecipe[] = [
"""
    if not recipes:
        body = "];\n\n"
    else:
        parts = []
        for r in recipes:
            lines = ["  {"]
            lines.append(f'    name: `{ts_escape(r["name"])}`,')
            for opt in ("servings", "prepTime", "cookTime", "notes"):
                if opt in r:
                    lines.append(f'    {opt}: `{ts_escape(r[opt])}`,')
            lines.append(f'    ingredients: `{ts_escape(r["ingredients"])}`,')
            lines.append(f'    directions: `{ts_escape(r["directions"])}`,')
            if r.get("categories"):
                cats = ", ".join(f'`{ts_escape(c)}`' for c in r["categories"])
                lines.append(f"    categories: [{cats}],")
            lines.append("  },")
            parts.append("\n".join(lines))
        body = "\n".join(parts) + "\n];\n\n"

    footer = """export function hasChatRecipes(): boolean {
  return ChatRecipes.length > 0;
}

function formatRecipe(r: ChatRecipe): string {
  const lines = [`### ${r.name}`];
  const meta: string[] = [];
  if (r.servings) meta.push(`Portionen: ${r.servings}`);
  if (r.prepTime) meta.push(`Vorbereitung: ${r.prepTime}`);
  if (r.cookTime) meta.push(`Garzeit: ${r.cookTime}`);
  if (r.categories?.length) meta.push(`Kategorien: ${r.categories.join(", ")}`);
  if (meta.length) lines.push(meta.join(" · "));
  lines.push("Zutaten:", r.ingredients.trim());
  lines.push("Zubereitung:", r.directions.trim());
  if (r.notes?.trim()) lines.push("Notizen:", r.notes.trim());
  return lines.join("\\n");
}

export function getChatRecipesKnowledge(): string {
  if (!hasChatRecipes()) return "";
  return [
    "KÜCHEN-REZEPTE (nur bei expliziten Rezept-Fragen im Chat nutzen; nicht von selbst erwähnen; in Ich-Form als Thomas; Schweizer Schreibweise):",
    "Antworte mit dem passenden Rezept aus dieser Liste. Wenn nach einem Gericht gefragt wird, das nicht hier steht: ehrlich sagen, dass es in den hinterlegten Rezepten nicht vorkommt, und ein anderes Signature-Gericht aus der Liste anbieten.",
    "",
    ...ChatRecipes.map(formatRecipe),
  ].join("\\n\\n");
}
"""
    return header + body + footer


def main() -> None:
    parser = argparse.ArgumentParser(description="Paprika → chatRecipes.ts")
    parser.add_argument("export", nargs="?", help="Pfad zu .paprikarecipes")
    parser.add_argument(
        "--category",
        help="Nur Rezepte mit dieser Paprika-Kategorie (z. B. Bewerbung)",
    )
    args = parser.parse_args()

    src = Path(args.export) if args.export else None
    archive = find_export(src)
    recipes = extract_recipes(archive, args.category)

    OUT.write_text(emit_ts(recipes), encoding="utf-8")
    print(f"OK: {len(recipes)} Rezepte aus {archive.name} -> {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
