/**
 * Küchen-Rezepte – nur für den Chatbot (System-Prompt + Backup-Antworten).
 * Nicht in der App-Oberfläche sichtbar.
 *
 * Befüllen:
 *   python scripts/import_paprika_recipes.py "Pfad/zu/Export.paprikarecipes"
 * Optional nur Kategorie «Bewerbung» in Paprika:
 *   python scripts/import_paprika_recipes.py Export.paprikarecipes --category Bewerbung
 */

export type ChatRecipe = {
  name: string;
  servings?: string;
  prepTime?: string;
  cookTime?: string;
  ingredients: string;
  directions: string;
  notes?: string;
  categories?: string[];
};

/** Auto-generated by scripts/import_paprika_recipes.py – leer bis erster Import */
export const ChatRecipes: ChatRecipe[] = [];

export function hasChatRecipes(): boolean {
  return ChatRecipes.length > 0;
}

function formatRecipe(r: ChatRecipe): string {
  const lines = [`### ${r.name}`];
  const meta: string[] = [];
  if (r.servings) meta.push(`Portionen: ${r.servings}`);
  if (r.prepTime) meta.push(`Vorbereitung: ${r.prepTime}`);
  if (r.cookTime) meta.push(`Garzeit: ${r.cookTime}`);
  if (r.categories?.length) meta.push(`Kategorien: ${r.categories.join(", ")}`);
  if (meta.length) lines.push(meta.join(" · "));
  lines.push("Zutaten:", r.ingredients.trim());
  lines.push("Zubereitung:", r.directions.trim());
  if (r.notes?.trim()) lines.push("Notizen:", r.notes.trim());
  return lines.join("\n");
}

export function getChatRecipesKnowledge(): string {
  if (!hasChatRecipes()) return "";
  return [
    "KÜCHEN-REZEPTE (nur bei expliziten Rezept-Fragen im Chat nutzen; nicht von selbst erwähnen; in Ich-Form als Thomas; Schweizer Schreibweise):",
    "Antworte mit dem passenden Rezept aus dieser Liste. Wenn nach einem Gericht gefragt wird, das nicht hier steht: ehrlich sagen, dass es in den hinterlegten Rezepten nicht vorkommt, und ein anderes Signature-Gericht aus der Liste anbieten.",
    "",
    ...ChatRecipes.map(formatRecipe),
  ].join("\n\n");
}
